# Copyright (c) 2026 Samsarix LLC
# SPDX-License-Identifier: MPL-2.0

"""Local-first, reviewable social campaign packaging by Samsarix."""

from ._version import __version__

from .models import (
    CampaignBundle,
    CampaignCheck,
    CampaignConfig,
    ConfigError,
    LinkTracking,
    MediaReference,
    PlatformContentVariant,
    PlatformDraft,
    QualityIssue,
)
from .quality import check_campaign
from .policy import (
    ContentPolicy,
    ContentPolicyBinding,
    ContentPolicyRule,
    evaluate_content_policy,
    load_content_policy,
)
from .review import (
    ApprovalCheck,
    ApprovalIssue,
    CampaignApproval,
    CampaignDiff,
    CampaignDraftChange,
    CampaignFieldChange,
    create_campaign_approval,
    diff_campaigns,
    export_campaign_approval,
    load_campaign_approval,
    parse_approval_timestamp,
    verify_campaign_approval,
)
from .plans import (
    CampaignPlan,
    CampaignPlanBundle,
    CampaignPlanCheck,
    CampaignPlanItem,
    PlanIssue,
    PlannedCampaign,
    build_campaign_plan,
    check_campaign_plan,
    export_campaign_plan,
    load_campaign_plan,
    render_plan_adapter,
    render_plan_calendar,
)
from .plan_review import (
    CampaignPlanApproval,
    CampaignPlanDiff,
    PlanApprovalCheck,
    PlanFieldChange,
    PlanItemChange,
    PlanItemSnapshot,
    create_campaign_plan_approval,
    diff_campaign_plans,
    export_campaign_plan_approval,
    load_campaign_plan_approval,
    verify_campaign_plan_approval,
)
from .handoff import (
    CampaignPlanHandoff,
    CampaignPlanHandoffPacket,
    HandoffArtifact,
    HandoffCheck,
    HandoffIssue,
    build_campaign_plan_handoff,
    export_campaign_plan_handoff,
    load_campaign_plan_handoff,
    verify_campaign_plan_handoff,
)
from .readiness import (
    CampaignPlanReadiness,
    CampaignPlanReadinessItem,
    ReadinessIssue,
    build_campaign_plan_readiness,
    export_campaign_plan_readiness_html,
    render_campaign_plan_readiness_html,
)
from .schema import (
    load_adapter_schema,
    load_approval_schema,
    load_campaign_schema,
    load_content_policy_schema,
    load_handoff_schema,
    load_plan_approval_schema,
    load_plan_schema,
    load_readiness_schema,
)
from .workflow import build_campaign, export_campaign, load_campaign

__all__ = [
    "__version__",
    "ApprovalCheck",
    "ApprovalIssue",
    "CampaignApproval",
    "CampaignBundle",
    "CampaignCheck",
    "CampaignConfig",
    "CampaignDiff",
    "CampaignDraftChange",
    "CampaignFieldChange",
    "CampaignPlan",
    "CampaignPlanApproval",
    "CampaignPlanBundle",
    "CampaignPlanCheck",
    "CampaignPlanDiff",
    "CampaignPlanHandoff",
    "CampaignPlanHandoffPacket",
    "CampaignPlanItem",
    "CampaignPlanReadiness",
    "CampaignPlanReadinessItem",
    "ConfigError",
    "ContentPolicy",
    "ContentPolicyBinding",
    "ContentPolicyRule",
    "HandoffArtifact",
    "HandoffCheck",
    "HandoffIssue",
    "LinkTracking",
    "MediaReference",
    "PlanApprovalCheck",
    "PlanFieldChange",
    "PlanItemChange",
    "PlanItemSnapshot",
    "PlanIssue",
    "PlannedCampaign",
    "PlatformContentVariant",
    "PlatformDraft",
    "QualityIssue",
    "ReadinessIssue",
    "build_campaign",
    "build_campaign_plan",
    "build_campaign_plan_handoff",
    "build_campaign_plan_readiness",
    "check_campaign",
    "check_campaign_plan",
    "create_campaign_approval",
    "create_campaign_plan_approval",
    "diff_campaigns",
    "diff_campaign_plans",
    "export_campaign",
    "export_campaign_approval",
    "export_campaign_plan",
    "export_campaign_plan_approval",
    "export_campaign_plan_handoff",
    "export_campaign_plan_readiness_html",
    "evaluate_content_policy",
    "load_adapter_schema",
    "load_approval_schema",
    "load_campaign",
    "load_campaign_approval",
    "load_campaign_plan",
    "load_campaign_plan_approval",
    "load_campaign_plan_handoff",
    "load_campaign_schema",
    "load_content_policy",
    "load_content_policy_schema",
    "load_handoff_schema",
    "load_plan_approval_schema",
    "load_plan_schema",
    "load_readiness_schema",
    "parse_approval_timestamp",
    "render_campaign_plan_readiness_html",
    "render_plan_adapter",
    "render_plan_calendar",
    "verify_campaign_approval",
    "verify_campaign_plan_approval",
    "verify_campaign_plan_handoff",
]
